- name: Build Docker image
  shell: docker build -t devops-app /opt/devops-project/app

- name: Remove old container
  shell: docker rm -f devops-container || true

- name: Run container
  shell: docker run -d -p 8085:80 --name devops-container devops-app
