apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      imagePullSecrets:
        - name: nexus-secret   # 🔐 pulls from Nexus
      containers:
        - name: devops-container
          image: 172.31.21.36:8082/devops-app:latest   # 🎯 Nexus image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
